name: Flutter

on:
  push:
    paths:
      - "lib/**"
      - "test/**"
      - "assets/**"
      - "tool/**"
      - ".vscode/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - "analysis_options.yaml"
      - "l10n.yaml"
      - ".github/workflows/flutter.yml"
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - "assets/**"
      - "tool/**"
      - ".vscode/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - "analysis_options.yaml"
      - "l10n.yaml"
      - ".github/workflows/flutter.yml"

jobs:
  analyze-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Resolve dependencies
        run: flutter pub get
      - name: Static analysis
        run: flutter analyze --fatal-infos
      - name: Unit and widget tests
        run: flutter test
